spring:
  datasource:
    url: jdbc:h2:mem:upload
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  devtools:
    livereload:
      enabled: true
    freemarker:
      cache: false
    restart:
      enabled: true
  thymeleaf:
    cache: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: [ 복사한 client-id ]
            client-secret: [ 복사한 client-secret ]
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/oauth2/callback/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

file:
  upload:
    path: C:\workspace\upload_folder   #로컬경로   환경변수로 하던가 하자.


jwt:
  secret: "k9D$w0t7vO@R3fAq%zX#8G1!bT6pLq@VnYcJ2r#U5xM8aW!e"











